import { createContext,useContext,useState,useEffect,useRef,type ReactNode } from 'react';
import { useServerFn } from '@tanstack/react-start';
import { services,STIPEND } from './support';
import { readWorkspace,saveWorkspace } from './workspace.functions';
import { toast } from 'sonner';
export type Student={id:string;firstName:string;lastName:string;email:string;phone?:string;state:string;campus:string;mode:'onsite'|'online';cardId:string;monthsEnrolled:number;monthlyStipend:number;subscriptions:string[];assignments:Record<string,string>;rooms?:Record<string,string>;createdAt:string;activity:{label:string;detail:string;at:string}[]};
export type CatalogService={id:string;name:string;description:string;price:number;modes:string[];tapAccess:boolean;archived?:boolean;icon:string};
export type Facility={id:string;name:string;kind:string;state:string;campus:string;capacity:number;rooms?:{id:string;name:string;capacity:number}[]};
export type Reader={id:string;label:string;facilityId:string;roomId:string;online:boolean};
export type Workspace={student:Student|null;students:Student[];catalog:CatalogService[];facilities:Facility[];readers:Reader[]};
export const states='Abia.Adamawa.Akwa Ibom.Anambra.Bauchi.Bayelsa.Benue.Borno.Cross River.Delta.Ebonyi.Edo.Ekiti.Enugu.FCT - Abuja.Gombe.Imo.Jigawa.Kaduna.Kano.Katsina.Kebbi.Kogi.Kwara.Lagos.Nasarawa.Niger.Ogun.Ondo.Osun.Oyo.Plateau.Rivers.Sokoto.Taraba.Yobe.Zamfara'.split('.');
export const campusFor=(state:string)=>state==='Lagos'?'Yaba Campus':state==='FCT - Abuja'?'Wuse Campus':'Ilorin Campus';
export const onsiteIds=['hub','meals','transport','accommodation'];
export function initialWorkspace():Workspace{const facilities:Facility[]=[['fac-hub-ilorin','Ilorin Learning Hall A','hub','Kwara',120],['fac-hub-ilorin-b','Ilorin Learning Hall B','hub','Kwara',80],['fac-hub-yaba','Yaba Learning Hall','hub','Lagos',150],['fac-hub-wuse','Wuse Learning Hall','hub','FCT - Abuja',90],['fac-acc-tanke','Tanke Hostel','accommodation','Kwara',60],['fac-acc-sabo','Sabo Residence','accommodation','Lagos',45],['fac-tra-ilorin','Ilorin Shuttle Route 1','transport','Kwara',40],['fac-tra-yaba','Yaba Shuttle Route 1','transport','Lagos',40],['fac-kit-ilorin','Ilorin Kitchen','kitchen','Kwara',200],['fac-kit-yaba','Yaba Kitchen','kitchen','Lagos',200]].map(([id,name,kind,state,capacity])=>({id:String(id),name:String(name),kind:String(kind),state:String(state),capacity:Number(capacity),campus:campusFor(String(state))}));const mainFacility=facilities[0];if(mainFacility)mainFacility.rooms=[{id:'room-ilorin-1',name:'Hall A1',capacity:60},{id:'room-ilorin-2',name:'Hall A2',capacity:40},{id:'room-ilorin-lab',name:'Hardware Lab',capacity:20}];const first='Amaka.Tunde.Zainab.Chidi.Halima.Emeka.Fatima.Segun.Ngozi.Ibrahim.Blessing.Yusuf.Adaeze.Kelechi.Aisha.Bashir.Temi.Ifeoma.Musa.Damilola.Grace.Obinna.Rukayat.Peter.Esther.Suleiman.Nkechi.Femi.Hauwa.Chinedu'.split('.'),last=['Okafor','Bello','Adeyemi','Eze','Musa','Nwosu','Abubakar','Ogunleye','Ibrahim','Okonkwo','Lawal','Aliyu','Balogun','Uche','Sani'];const students:Student[]=Array.from({length:48},(_,i)=>{const state=['Kwara','Lagos','FCT - Abuja','Oyo','Kano','Rivers','Enugu'][i%7]??'Kwara',mode=i%4===3?'online':'onsite',campus=mode==='online'?'Remote':campusFor(state),subscriptions=services.filter(s=>mode==='onsite'||!onsiteIds.includes(s.id)).filter((_,j)=>(i+j*3)%4!==0).map(s=>s.id);return{id:'stu-'+(i+1),firstName:first[i%30]??'Amaka',lastName:last[i*5%15]??'Okafor',email:(first[i%30]??'Amaka').toLowerCase()+'.'+(last[i*5%15]??'Okafor').toLowerCase()+'@learn2earn.ng',state,campus,mode,cardId:'L2E-2026-'+(2000+i),monthsEnrolled:1+i*7%11,monthlyStipend:STIPEND,subscriptions,assignments:Object.fromEntries(facilities.filter(f=>f.campus===campus&&(f.kind==='hub'||subscriptions.includes(f.kind))).map(f=>[f.kind,f.id])),createdAt:'2026-01-01T00:00:00Z',activity:[]};});return{student:null,students,catalog:services.map(s=>({...s,icon:s.id,modes:onsiteIds.includes(s.id)?['onsite']:['onsite','online'],tapAccess:onsiteIds.includes(s.id)})),facilities,readers:[...facilities.map((f,i)=>({id:'RDR-'+(1001+i),label:f.name+' — main door',facilityId:f.id,roomId:'',online:i%7!==3})),...(mainFacility?.rooms??[]).map((r,i)=>({id:'RDR-'+(1101+i),label:r.name+' door',facilityId:mainFacility?.id??'fac-hub-ilorin',roomId:r.id,online:i!==2}))]};}
const Context=createContext<{data:Workspace;ready:boolean;update:(fn:(w:Workspace)=>Workspace)=>void}|null>(null);
export function WorkspaceProvider({children}:{children:ReactNode}){const [data,setData]=useState(initialWorkspace),[ready,setReady]=useState(false);const read=useServerFn(readWorkspace),save=useServerFn(saveWorkspace),changed=useRef(false);useEffect(()=>{read().then(value=>{if(value)setData(value as unknown as Workspace);setReady(true);}).catch(()=>{setReady(true);toast.error('Cloud unavailable. Changes may not be saved.');});},[]);useEffect(()=>{if(!ready||!changed.current)return;const timer=setTimeout(()=>{save({data:{payload:data as unknown as Record<string,unknown>}}).catch(()=>toast.error('Could not save changes. Please try again.'));},350);return()=>clearTimeout(timer);},[data,ready]);return <Context.Provider value={{data,ready,update:fn=>{changed.current=true;setData(fn);}}}>{children}</Context.Provider>}
export function useWorkspace(){const ctx=useContext(Context);if(!ctx)throw new Error('Workspace unavailable');return ctx;}
export const total=(ids:string[],catalog:CatalogService[])=>catalog.filter(s=>ids.includes(s.id)).reduce((a,s)=>a+s.price,0);
